addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.3.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"  % "0.9.11")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.11")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"       % "0.3.7")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"      % "2.1.3")
addSbtPlugin("org.scoverage"             % "sbt-scoverage" % "1.6.1")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"       % "2.0.0-M2")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"  % "3.8.1")
