addSbtPlugin("ch.epfl.lamp"              % "sbt-dotty"    % "0.4.1")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"      % "0.3.7")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.4.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix" % "0.9.17")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.11")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"     % "2.2.2")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"      % "2.0.1")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype" % "3.9.2")
